
name: flutter_examples
description: This project contains the Syncfusion Flutter UI widgets examples.
version: 32.1.19
homepage: https://github.com/syncfusion/flutter-examples

environment:
  sdk: ^3.7.0
  flutter: '>=3.35.1'

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/pdf/
    - images/xlsio/
    - images/pdf_viewer/
    - assets/pdf/
    - lib/sample_details.json
    - assets/world_map.json
    - assets/africa.json
    - assets/europe.json
    - assets/germany.json
    - assets/india.json
    - assets/usa.json
    - assets/south_america.json
    - assets/australia.json
    - assets/maps_brazil_boundary.json
    - assets/maps_uk_boundary.json
    - assets/maps_france_boundary.json
    - assets/river.json
    - assets/london_to_british.json
    - assets/london_to_chessington.json
    - assets/london_to_hampton_court_palace.json
    - assets/london_to_twickenham_stadium.json
    - assets/london_to_windsor_castle.json
    - assets/product_data.json
    - assets/chart_data.json
    - assets/microsoft.png
    - assets/google.png
    - assets/amazon.png
    - assets/tesla.png
    - assets/export_icon.png
    - assets/screen_cover.png
    - assets/stock_data/apple.json
    - assets/stock_data/facebook.json
    - assets/stock_data/google.json
    - assets/stock_data/microsoft.json
    - assets/stock_data/nestle.json
    - assets/stock_data/netflix.json
    - assets/stock_data/tesla.json
    - assets/stock_logo/apple.svg
    - assets/stock_logo/facebook.svg
    - assets/stock_logo/google.svg
    - assets/stock_logo/microsoft.svg
    - assets/stock_logo/nestle.svg
    - assets/stock_logo/netflix.svg
    - assets/stock_logo/tesla.svg
    - assets/stock_logo/app_logo.svg
    - assets/stock_logo/cover_image.png
  fonts:
    - family: Expense Tracker Icons
      fonts:
        - asset: assets/font_icon/expense_tracker_icon.ttf
    - family: HeeboBold
      fonts:
        - asset: assets/fonts/Heebo-Bold.ttf
    - family: HeeboMedium
      fonts:
        - asset: assets/fonts/Heebo-Medium.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Stock Analysis Font Icon
      fonts:
        - asset: assets/fonts/Stock Analysis Font Icon.ttf

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  web: ^1.1.0
  provider: ^6.1.2
  flutter_svg: ^2.1.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  desktop_window: 0.4.2
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  intl: ">=0.18.1 <0.21.0"
  shared_preferences: ^2.5.1
  flutter_markdown: ^0.7.4+1
  google_generative_ai: ^0.4.6
  path_provider_foundation: ^2.1.0
  syncfusion_localizations: ^32.1.19
  syncfusion_flutter_datagrid_export: ^32.1.19
  syncfusion_flutter_calendar: ^32.1.19
  syncfusion_flutter_datepicker: ^32.1.19
  syncfusion_flutter_charts: ^32.1.19
  syncfusion_flutter_gauges: ^32.1.19
  syncfusion_flutter_sliders: ^32.1.19
  syncfusion_flutter_pdf: ^32.1.19
  syncfusion_flutter_barcodes: ^32.1.19
  syncfusion_officechart: ^32.1.19
  syncfusion_flutter_maps: ^32.1.19
  syncfusion_flutter_signaturepad: ^32.1.19
  syncfusion_flutter_pdfviewer: ^32.1.19
  syncfusion_flutter_treemap: ^32.1.19
  syncfusion_flutter_chat: ^32.1.19
