name: flutter_examples
description: This project contains the Syncfusion Flutter UI widgets examples.
version: 18.4.30
author: Syncfusion <support@syncfusion.com>
homepage: https://github.com/syncfusion/flutter-examples

environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:
  flutter_test:
    sdk: flutter
  flutter:
    sdk: flutter
  url_launcher: ^5.0.3
  intl: ^0.16.0
  path_provider: ^1.6.18

  syncfusion_flutter_datagrid: ^18.4.35-beta
  syncfusion_flutter_calendar: ^18.4.30
  syncfusion_flutter_datepicker: ^18.4.30-beta
  syncfusion_flutter_charts: ^18.4.30
  syncfusion_flutter_gauges: ^18.4.30
  syncfusion_flutter_sliders: ^18.4.30-beta
  syncfusion_flutter_pdf: ^18.4.30-beta
  syncfusion_flutter_barcodes: ^18.4.30
  syncfusion_officechart: ^18.4.30-beta
  syncfusion_flutter_maps: ^18.4.30-beta
  syncfusion_flutter_signaturepad: ^18.4.30-beta
  syncfusion_flutter_pdfviewer: ^18.4.30-beta


flutter:
  uses-material-design: true
  assets:
    - images/
    - images/pdf/
    - images/xlsio/
    - assets/pdf/
    - lib/sample_details.json
    - world_map.json
    - africa.json
    - europe.json
    - india.json
    - usa.json
    - south_america.json
    - australia.json
    - river.json
    - london_to_british.json
    - london_to_chessington.json
    - london_to_hampton_court_palace.json
    - london_to_twickenham_stadium.json
    - london_to_windsor_castle.json
    - product_data.json
    - chart_data.json
  fonts:
    - family: HeeboBold
      fonts:
        - asset: assets/fonts/Heebo-Bold.ttf
    - family: HeeboMedium
      fonts:
        - asset: assets/fonts/Heebo-Medium.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
