name: flutter_examples
description: This project contains the Syncfusion Flutter UI widgets examples.
version: 19.1.63
homepage: https://github.com/syncfusion/flutter-examples

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_test:
    sdk: flutter
  flutter:
    sdk: flutter
  url_launcher: ^6.0.2
  path_provider: ^2.0.1
  path_provider_macos: ^2.0.0
  desktop_window: 0.4.0


  syncfusion_flutter_datagrid: ^19.1.67-beta 
  syncfusion_flutter_calendar: ^19.1.67
  syncfusion_flutter_datepicker: ^19.1.67-beta 
  syncfusion_flutter_charts: ^19.1.67
  syncfusion_flutter_gauges: ^19.1.67 
  syncfusion_flutter_sliders: ^19.1.67-beta
  syncfusion_flutter_pdf: ^19.1.67-beta
  syncfusion_flutter_barcodes: ^19.1.67
  syncfusion_officechart: ^19.1.67-beta
  syncfusion_flutter_maps: ^19.1.67-beta
  syncfusion_flutter_signaturepad: ^19.1.67-beta
  syncfusion_flutter_pdfviewer: ^19.1.67-beta
  syncfusion_flutter_treemap: ^19.1.67-beta

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/pdf/
    - images/xlsio/
    - assets/pdf/
    - lib/sample_details.json
    - world_map.json
    - africa.json
    - europe.json
    - india.json
    - usa.json
    - south_america.json
    - australia.json
    - maps_brazil_boundary.json
    - maps_uk_boundary.json
    - maps_france_boundary.json
    - river.json
    - london_to_british.json
    - london_to_chessington.json
    - london_to_hampton_court_palace.json
    - london_to_twickenham_stadium.json
    - london_to_windsor_castle.json
    - product_data.json
    - chart_data.json
  fonts:
    - family: HeeboBold
      fonts:
        - asset: assets/fonts/Heebo-Bold.ttf
    - family: HeeboMedium
      fonts:
        - asset: assets/fonts/Heebo-Medium.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
